version: '3'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass-coder
      MYSQL_DATABASE: db-coder
    ports:
      - "3306:3306"